### ISSUE TITLE
Can this be used with a regular PCB

### ISSUE THREAD

**Issue by kandji-edwin** [andimoto/keebcu#9]
Awesome project! Can this be used with a regular keyboard PCB, or is it only suitable for hand wired keys attached to an Arduino?

In particular, I have an Makerdiary M60: https://makerdiary.com/collections/mechanical-keyboard

**Comment by andimoto** [comment]
Thanks! 
I think it could work with some modifications:
- PCB should fit inside the case
- USB cut-out should be placed correctly
- Stand-offs for the lid screws should be much lower, and also placed to fit some holes of the pcb
- Bigger Problem: fixing the lid properly to the case (because screw stand-offs would be smaller and already fixing the pcb inside). Maybe it works if pcb gets fixed by some hex spacers and the lid gets fixed on top of that....

Just a few ideas...

**Comment by kandji-edwin** [comment]
Thanks for the tips. While I'm a programmer by trade, I've only just started 3d printing and using openscad 2 weeks ago. 

I'll keep you posted on how my attempt goes, though
